import React, { useState } from 'react';
import { Copy, Play } from 'lucide-react';

const CodeGenerator = () => {
  const [prompt, setPrompt] = useState('');
  const [language, setLanguage] = useState('javascript');
  const [generatedCode, setGeneratedCode] = useState('');

  const handleGenerate = () => {
    setGeneratedCode(`// Sample ${language} code generated by AI\n\nfunction example() {\n  console.log("Hello from AI Code Generator!");\n  // Your custom logic here...\n}`);
  };

  return (
    <div className="p-6 bg-gray-50 min-h-screen">
      <h1 className="text-3xl font-bold text-gray-800 mb-2">AI Code Generator</h1>
      <p className="text-gray-600 mb-8">Generate clean code in any programming language</p>

      <div className="max-w-5xl mx-auto grid grid-cols-1 lg:grid-cols-5 gap-6">
        <div className="lg:col-span-2 bg-white rounded-3xl p-6">
          <select
            value={language}
            onChange={(e) => setLanguage(e.target.value)}
            className="w-full mb-4 p-3 border border-gray-300 rounded-xl"
          >
            <option value="javascript">JavaScript</option>
            <option value="python">Python</option>
            <option value="react">React JSX</option>
            <option value="tailwind">Tailwind CSS</option>
          </select>

          <textarea
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            rows="10"
            className="w-full border border-gray-300 rounded-2xl p-5"
            placeholder="Create a login form with validation..."
          />

          <button onClick={handleGenerate} className="mt-6 w-full bg-emerald-600 text-white py-4 rounded-2xl hover:bg-emerald-700">
            Generate Code
          </button>
        </div>

        <div className="lg:col-span-3 bg-white rounded-3xl p-6">
          <div className="flex justify-between mb-4">
            <h2 className="font-semibold">Generated Code</h2>
            <button className="text-emerald-600"><Copy size={20} /></button>
          </div>
          <pre className="bg-gray-900 text-gray-100 p-6 rounded-2xl overflow-auto h-[460px] text-sm">
            {generatedCode || "// Your code will appear here"}
          </pre>
        </div>
      </div>
    </div>
  );
};

export default CodeGenerator;